/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jyyu' at '7/23/15 11:11 PM' with Gradle 2.5
 *
 * @author jyyu, @date 7/23/15 11:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
